import { createHash, randomUUID } from "node:crypto";
import { getDatabase } from "../database";
import { canonicalizeJson, WorkflowValidationError } from "../workflows/compiler";
import type { JsonValue, ResourceKind } from "../workflows/contracts";

const tables: Record<ResourceKind, { parent: string; versions: string; foreign: string }> = {
  agents: { parent: "agent_definitions", versions: "agent_definition_versions", foreign: "agent_definition_id" },
  skills: { parent: "skill_definitions", versions: "skill_definition_versions", foreign: "skill_definition_id" },
  mcps: { parent: "mcp_definitions", versions: "mcp_definition_versions", foreign: "mcp_definition_id" },
};
function body(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new WorkflowValidationError(""); const result = value as Record<string, unknown>; if (typeof result.name !== "string" || !result.name) throw new WorkflowValidationError("name"); if (!result.definition || typeof result.definition !== "object" || Array.isArray(result.definition)) throw new WorkflowValidationError("definition"); return result; }
function table(kind: string) { if (!(kind in tables)) return null; return tables[kind as ResourceKind]; }
export async function listResources(kind: string) { const target = table(kind); if (!target) return null; const rows = await getDatabase().unsafe(`SELECT parent.id, parent.name, parent.archived_at, version.id AS version_id, version.version, version.definition, version.hash FROM ${target.parent} parent LEFT JOIN LATERAL (SELECT id, version, definition, hash FROM ${target.versions} WHERE ${target.foreign}=parent.id ORDER BY version DESC LIMIT 1) version ON true ORDER BY parent.name, parent.id`); return { resources: rows.map((row) => ({ id: row.id, name: row.name, archivedAt: row.archived_at, latestVersion: row.version_id ? { id: row.version_id, version: row.version, definition: row.definition, hash: row.hash } : null })) }; }
export async function createResource(kind: string, value: unknown) { const target = table(kind); if (!target) return null; const input = body(value); const canonical = canonicalizeJson(input.definition as JsonValue); const hash = createHash("sha256").update(canonical).digest("hex"); const id = `${kind.slice(0, -1)}-${randomUUID()}`; const sql = getDatabase(); return sql.begin(async (transaction) => { await transaction.unsafe(`INSERT INTO ${target.parent} (id, name) VALUES ($1, $2)`, [id, input.name as string]); const [version] = await transaction.unsafe(`INSERT INTO ${target.versions} (id, ${target.foreign}, version, definition, canonical_json, hash) VALUES ($1, $2, 1, $3, $4, $5) RETURNING id, version, definition, hash`, [`${kind.slice(0, -1)}-version-${randomUUID()}`, id, JSON.stringify(input.definition), canonical, hash]); return { resource: { id, name: input.name as string, archivedAt: null }, latestVersion: version }; }); }
export async function updateResource(kind: string, id: string, value: unknown) { const target = table(kind); if (!target) return null; const input = body(value); const canonical = canonicalizeJson(input.definition as JsonValue); const hash = createHash("sha256").update(canonical).digest("hex"); const sql = getDatabase(); return sql.begin(async (transaction) => { const [parent] = await transaction.unsafe(`SELECT id FROM ${target.parent} WHERE id=$1 FOR UPDATE`, [id]); if (!parent) return null; await transaction.unsafe(`UPDATE ${target.parent} SET name=$2, archived_at=NULL WHERE id=$1`, [id, input.name as string]); const [latest] = await transaction.unsafe(`SELECT COALESCE(MAX(version), 0)::int AS version FROM ${target.versions} WHERE ${target.foreign}=$1`, [id]); const [version] = await transaction.unsafe(`INSERT INTO ${target.versions} (id, ${target.foreign}, version, definition, canonical_json, hash) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,version,definition,hash`, [`${kind.slice(0, -1)}-version-${randomUUID()}`, id, latest.version + 1, JSON.stringify(input.definition), canonical, hash]); return { resource: { id, name: input.name as string, archivedAt: null }, latestVersion: version }; }); }
export async function archiveResource(kind: string, id: string) { const target = table(kind); if (!target) return null; const rows = await getDatabase().unsafe(`UPDATE ${target.parent} SET archived_at=now() WHERE id=$1 AND archived_at IS NULL RETURNING id`, [id]); return rows.length === 1; }
