#!/usr/bin/env bash
# Create a git worktree branched from the latest remote main, fully ready to
# develop: correct Node version, independent node_modules, and an isolated
# dev-server environment (ports + SQLite data dir) derived from the worktree
# name so multiple worktrees can run `pnpm dev` concurrently without conflicts.
#
# Usage: scripts/create-worktree.sh <type> <name>
#   <type> ∈ feat | fix | chore | research | docs
#   <name> kebab-case short identifier
#
# Example:
#   scripts/create-worktree.sh chore merge-base-check
#   → fetches origin, creates .worktrees/merge-base-check on branch
#     chore/merge-base-check, installs deps under Node 22, and writes a .env
#     with PORT=4001+offset, FAKE_PROVIDER_PORT=4510+offset,
#     WORKFLOW_DATA_DIR=~/.config/workflow-dev-merge-base-check

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if [ $# -ne 2 ]; then
  echo "Usage: $0 <type> <name>"
  echo "  <type> ∈ feat | fix | chore | research | docs"
  echo "  <name> kebab-case short identifier"
  exit 1
fi

TYPE="$1"
NAME="$2"

case "$TYPE" in
  feat|fix|chore|research|docs) ;;
  *)
    echo "Error: invalid type '$TYPE'. Must be one of: feat fix chore research docs"
    exit 1
    ;;
esac

BRANCH="${TYPE}/${NAME}"
WORKTREE_DIR=".worktrees/${NAME}"

if [ -d "$WORKTREE_DIR" ]; then
  echo "Error: worktree directory '$WORKTREE_DIR' already exists."
  exit 1
fi

# --- Node 22 enforcement ---
# The machine's nvm default may point at another major (e.g. 25). better-sqlite3
# has no prebuilt binding for non-LTS ABIs and will fail at runtime. All scripts
# that touch Node must ensure 22 is active.
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  # shellcheck source=/dev/null
  source "$NVM_DIR/nvm.sh"
  nvm use 22 >/dev/null 2>&1 || { echo "Error: Node 22 is not installed. Run: nvm install 22"; exit 1; }
else
  echo "Warning: nvm not found. Ensure you are running Node 22 (got: $(node --version 2>/dev/null || echo 'none'))."
fi

echo "→ Fetching latest from origin..."
git fetch origin

echo "→ Creating worktree: $WORKTREE_DIR (branch: $BRANCH, base: origin/main)"
git worktree add --no-track -b "$BRANCH" "$WORKTREE_DIR" origin/main

# --- Install dependencies (independent node_modules under Node 22) ---
echo "→ Installing dependencies (pnpm install)..."
(cd "$WORKTREE_DIR" && pnpm install)

# --- Generate isolated .env ---
# Derive deterministic ports from the worktree name via CRC32 (cksum).
# Range: server 4001–4500, fake-provider 4510–5009 (500-slot gap, no overlap).
OFFSET=$(( $(echo -n "$NAME" | cksum | cut -d' ' -f1) % 500 ))
DEV_PORT=$(( 4001 + OFFSET ))
FAKE_PORT=$(( 4510 + OFFSET ))
DATA_DIR="$HOME/.config/workflow-dev-${NAME}"

cat > "$WORKTREE_DIR/.env" <<EOF
# Auto-generated by scripts/create-worktree.sh — isolated dev environment.
# Ports are derived from worktree name '$NAME' (offset=$OFFSET).
# Delete this file to fall back to defaults (4001/4010) if no conflict.
FAKE_PROVIDER_API_KEY=fake-provider-local
PORT=$DEV_PORT
FAKE_PROVIDER_PORT=$FAKE_PORT
WORKFLOW_DATA_DIR=$DATA_DIR
EOF

echo ""
echo "✓ Ready. Work in: $WORKTREE_DIR"
echo "  cd $WORKTREE_DIR"
echo ""
echo "  Dev server:  http://localhost:$DEV_PORT"
echo "  Fake provider: http://localhost:$FAKE_PORT"
echo "  Data dir:    $DATA_DIR"
